[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "ADA Database Guidelines for Developers"
authors = [{name = "Peng Ji", email = "pengji@ldeo.columbia.edu"}]
dynamic = ["version", "description"]
